- lib/servo.js
- test/servo.js
Issue:
When calling Servo.to with the same value for degrees twice in a row, the servo wouldn't fail.  Instead it went to 0 degrees.
> Fix Servo.to

- .travis.yml
- Gruntfile.js
- docs/ir-distance.md
- package.json
- Not added to the default task as it relies on your changes to be committed and causes the docs to be generated. This is fine on our CI but not ok in local development.
- Add to circle as a before_script because of the previous point
- ir-distance.md was out of date
> Add grunt test-docs to ensure docs are up to date

- lib/button.js
Fixes #587 
Prevents “cross-debouncing” of events across button instances.
**Don't merge yet.** - I don't have hardware with me to test.
> Move debounce function to constructor

- README.md
- docs/tinkerkit-thermistor.md
- eg/tinkerkit-thermistor.js
- lib/temperature.js
- test/temperature.js
- tpl/titles.json
I was hacking the other day with a Tinkerkit thermistor and I realized that it wasn't ever included in the `Temperature` controllers list.  
- Updated the controllers to include the Tinkerkit
- Updated the example to use the `Temperature` class
- Added the file to `titles.json`.  It was missing and `grunt examples` failed to create the MD because of it.
> Migrating the Tinkerkit Thermistor to be included in Temperature component

- .jscsrc
- Gruntfile.js
- util/xbee.js
- created `jscs` npm script target; `npm run-script jscs`
- removed JSCS config from `Gruntfile.js`; config now lives in `.jscsrc`
- added `jscs` as devDependency
- added `util/` to paths covered by JSCS
- fixed JSCS errors in `util/xbee.js`
- a couple formatting problems
- you can't `return` a `process.exit()` call
- fixed what appeared to be a logic error when no port name specified; would exit too early
- the above three issues were reported by JSCS
> extract jscs config into .jscsrc; resolves #632

- docs/led-rgb-anode.md
- eg/led-rgb-anode.js
- lib/led.js
- test/led.js
Fixes #629 
Confirmed working with `PCA9685` and `DEFAULT` controllers
> Add isAnode to LED state. Fixes gh-629

- docs/magnetometer-log.md
- docs/magnetometer-north.md
- eg/magnetometer-log.js
- eg/magnetometer-north.js
- eg/nodeconf-compass.js
- lib/board.js
- package.json
Related: #626 
Since chalk doesn't support the `orange` color I used the `reverse` for failure messages but I'm open to suggestion on what color to use here, this also fixes a couple of examples using colors and remove some unused colors logic from one example (`eg/magnetometer-north.js`)
> Migrate from colors.js to chalk

- README.md
- tpl/.readme.md
The "Why JavaScript" section accidentally got moved back under Supported Hardware section in a recent commit. Putting it back where it goes.
> Why Javascript moved back out of hardware section

- docs/led-pulse.md
- eg/led-pulse.js
Reverts rwaldron/johnny-five#660 The code was correct. The Fritzing diagram is what was wrong. Pin 13 on Uno is not PWM capable.
> Revert "Update LED Pulse example"

- Gruntfile.js
- lib/board.js
- lib/esc.js
- lib/led.js
- lib/pin.js
- lib/servo.js
- test/board.component.js
- test/board.js
- test/bootstrap.js
- test/pin.js
- test/repl.js
- Relevant files check `process.env.IS_TEST_MODE` instead of a global prop
- The value of `IS_TEST_MODE` is assumed to be a boolean
- Individual suites do not set `IS_TEST_MODE`
- `bootstrap.js` is no longer necessary and has been removed
- `Gruntfile.js` sets the `IS_TEST_MODE` flag; as long as you run the tests via `npm test` or `grunt`, your environment will be correct.  Otherwise, you must manually set the `IS_TEST_MODE` environment variable.
- simplified test targets within `Gruntfile.js` with globs
- remove `bootstrap.js` reference within `nodeunit:just`; while I was in there, corrected a potential Windows incompatibility, made slightly more flexible, and documented it for use with `grunt --help`
Happy to remove the changes I snuck into `Gruntfile.js` if you wish.
> use environment to declare test mode flag; resolves #669

- lib/servo.js
- test/servo.js
Addresses #666
1) Range was being constrained after offset was applied which was
wrong. User should not have to think in two different coordinate spaces.
2) Invert was based on global coordinate range which led to incorrect
values being passed to the servo. Invert has to be based on the
physical range of the servo in local coordinate space. We need to
track two ranges, the global coordinate range for ease of use and the
physical device range of the servo. We are assuming 180° servos for
now. We will have to add in 45° and 270° servos as Devices.
3) Added tests
> Fixes to servo

- lib/reflectancearray.js
- test/reflectancearray.js
Instead of an explicit calibration step, or the requirement to load a calibration file, setting `autoCalibrate: true` will cause the unit to always be calibrating.  This will make the learning curve on the sensor to be less steep because they don't need to worry about calibrating.  Instead, as long as the unit is reading data, it will be setting the min/max.  This will also help in environments like Robotnik, where the pre-ready code becomes awkward.
Users can still tweak the calibration by using the original mechanism.  This is just easier with less control.  
We are using a similar mechanism in the `Accelerometer`, and I was quite fond of it after it was complete.
> Support auto-calibration for reflectance array

- lib/servo.js
- test/servo.js
This got lost in 89be18da167c798ac9ec4fd27da371488c794e84
I'm using this ability liberally in complex Animation() scripts including my examples in the book.
> Restore ability to have Servo.Arrays be elements of Servo.Arrays

- docs/temperature-ds18b20.md
- eg/temperature-ds18b20.js
- eg/temperature-dual-ds18b20.js
- lib/fn.js
- lib/temperature.js
- test/temperature.js
This is to fix the bug https://github.com/rwaldron/johnny-five/issues/692
In order to support more than one DS18B20 OneWire sensors, we need to coordinate the OneWire requests to read so that they aren't clobbering each other.  I'm using the "Driver" approach that we used with the IMU where there may be multiple components/controllers, but they all use the same instance of a "driver" to coordinate a single resource.  In the case of the IMU, it was the single-unit I2C board.  In the case of this OneWire device, it is the OneWire bus itself.
I'm going to do a bit more manual testing tonight to make sure everything is good, but I think this code is solid enough for a PR.  I'll make minor tweaks if necessary.
> Multi ds18b20

- lib/led/led.js
- test/led.js
Ref #716 
Note that the callback is invoked after the LED is toggled, and we're using `setInterval()`, not nested `setTimeout()`, so the possible drift mentioned in https://github.com/rwaldron/johnny-five/issues/716#issuecomment-91623969 is unlikely to occur.
> Led: Add a callback for .blink()

- lib/led/led.js
- test/led.js
Animation intervals weren't cleared until another animation started or `.stop()` was called. As a result, once the animation completed, the interval would keep running and the `step` and `complete` callbacks would be called repeatedly.
> Led: Clear interval after animation

- lib/wii.js
There are uses of `opts` which require it to exist prior to these lines, so the guard isn't necessary.
> Wii: Remove check for opts existing before use

- lib/stepper.js
- test/stepper.js
Fixes #739 - limits max steppers (currently 6) per board instead of global
Fixes #736 - returns error object to callback function
> stepper max per board; err if no dir; tests

- lib/board.options.js
I noticed that `Array.isArray(arg)` was called multiple times, even though the result was already stored in a variable. I was about to just swap out the function call for the existing variable when I realized that the logic would be more clear by just adding another conditional.
> Minor cleanup for Board.Options

- test/motor.js
I noticed this when looking at cb14000c9440c2b3c8b77fa636f063597c53571c.
> Remove an unused spy in the motor tests

- lib/led/led.js
- lib/led/rgb.js
- test/led.js
Ref #742 
The initial work is done. `Led.RGB` now uses the device/controller model and has full support for direct use and PCA9685. I'll be adding support for BlinkM and Esplora controllers as well. Since the majority of the work is already done, I figured I'd file the PR now to start getting feedback.
> Led.RGB: Refactor to device/controller model

- lib/led/rgb.js
- test/led.js
Fixes #782 
I tested with a common cathode RGB LED as well, but didn't see the problem. The C code does have a special value for both though, so let me know if you'd like me to add the other case as well.
> Led.RGB: Handle special value for fully off common anode LEDs

- CONTRIBUTING.md
- docs/motor.md
- eg/motor.js
This commit also adds a oneliner stop() example.
> Motor doc: fix wrong comment

- test/extended/led.js
Was causing extended tests to fail.
> Interval is no longer a property on LED's

- docs/tinkerkit-accelerometer.md
- docs/tinkerkit-blink.md
- docs/tinkerkit-button.md
- docs/tinkerkit-continuous-servo.md
- docs/tinkerkit-joystick.md
- docs/tinkerkit-linear-pot.md
- docs/tinkerkit-rotary.md
- docs/tinkerkit-thermistor.md
- docs/tinkerkit-tilt.md
- docs/tinkerkit-touch.md
- eg/tinkerkit-accelerometer.js
- eg/tinkerkit-blink.js
- eg/tinkerkit-button.js
- eg/tinkerkit-continuous-servo.js
- eg/tinkerkit-joystick.js
- eg/tinkerkit-linear-pot.js
- eg/tinkerkit-rotary.js
- eg/tinkerkit-thermistor.js
- eg/tinkerkit-tilt.js
- eg/tinkerkit-touch.js
The TinkerKit examples have links to the parts needed for the examples.  The http://www.tinkerkit.com website went dark around mid-2014 it looks like.
I updated to the http://tinkerkit.tihhs.nl/ domain and all of the examples now link appropriately.
> Updated the tinkerkit examples with working website.

- docs/motor-hbridge.md
- eg/motor-hbridge.js
Make forward and reverse in the example both use a value of 255. 50 was so slow that it made it seem like the motor was just stuttering and not working properly in reverse.
> make fw/rev both 255

- parts.md
I was browsing through parts.md, and found a lot of broken, replaced, and retired links.  I updated things where I could, though some are now pointing at search result pages instead of specific products.
> Update broken and outdated links for parts.md

- lib/temperature.js
- test/temperature.js
This code adds an `aref` property to the `Temperature` object.  Defaults to whatever is defined on `this.io.aref` OR `5` if not defined at all.
This allows you to set the analog reference voltage for analog style temp controllers, first implementation I targeted the `TMP36` and will add to the rest of the analog controllers before we land this PR if this first one went well.
> Temperature: add analog reference to TMP36 controller

- lib/johnny-five.js
This is a fix for https://github.com/nebrius/raspi-io/issues/33.
tl;dr, pins are usually expressed as strings for the RPi because it's pin naming scheme is wack. Currently, it thinks this is giving the constructor a dictionary of options, instead of a pin name:
```
new five.Sensor.Digital('GPIO6');
```
This PR allows pins to be number _or_ strings, but assumes everything else is a dictionary of options.
> Allow digital sensor constructor to take string pin names

- .npmignore
Changeset 817bc77924500c6351b4cf5d00fac00e8a191a5b breaks modules which relied on the presence of the `mock-firmata` module.
Please accept this PR until #735 can be resolved properly...
> remove test/ from .npmignore due to #735

- docs/servo-continuous.md
- eg/servo-continuous.js
- lib/servo.js
- test/servo.js
I can think of no reason why we would not want this to happen. Servo state is a crap shoot otherwise.
> Stop continuous rotation servo on instantiation

- docs/sensor-fsr.md
- eg/sensor-fsr.js
Hi! 
`this.value` outputs a really small value which doesn't reflect on the led :|. 
`this.scaled` seems to work better with this example :star2: :tada:
> changing this.value to this.scaled to reflect light sensitivity

- lib/led/led.js
This will reduce visible PWM flashing with the PCA9685. Mostly noticeable when recording video but also visible with the eye under certain circumstances.
> Increase PWM frequency for PCA9685

- lib/animation.js
- test/animation.js
- test/extended/animation.js
temporal uses 100% of the CPU so on long running animations we switch to setInterval instead of temporal (after five seconds). 
Does five seconds seem good? It's completely arbitrary.
Tests look good but I still want to try with hardware so don't land this yet.
> Add temporalFallback

- lib/led/ledcontrol.js
- test/ledcontrol.js
Fixes #1003. This brings the API in line with the [datasheet's described blink functionality](https://www.adafruit.com/datasheets/ht16K33v110.pdf) (page 10).
> Fix blinking for the HT16K33 LED controller.

- package.json
lodash 4.0.0 dropped `pluck` method, so until it can be updated to use `map` drop to 3.10.1
> set version of lodash

- lib/board.js
- package.json
I submitted a very similar and related pull request for the Firmata module (https://github.com/jgautier/firmata/pull/108). If both PRs are merged in, NW.js v0.13 and Johnny-Five would work together right out of the box. The huge gain is that it would no longer be necessary to custom-compile node-serialport for NW.js (which is prohibitively complicated for beginners).
With the small changes I'm suggesting in this PR and the one for Firmata, I was able to successfully use Arduino + browser-serialport + Firmata + Johnny-Five + NW.js. This is an amazingly powerful combination for physical computing and robotics.
> Add browser-serialport dependency for NW.js support via Firmata

- lib/led/rgb.js
- test/led.js
After  a discussion with @rwaldron at the recent Nodebots NYC meetup, I wanted to add support for CSS color names when setting the color of an RGB LED.  As it turns out, one of the already available dependencies, `color-convert`, can do that for us.  This could be useful for people not comfortable with hex color codes.  
Example usage:
```
// Initialize the RGB LED
var led = new five.Led.RGB({
pins: {
red: 6,
green: 5,
blue: 3
}
});
// Turn it on and set the initial color
led.on();
led.color("green");
```
> Add support for CSS color names to RGB.color()

- tpl/.readme.md
Node Open Pilot is an opensource software and openhardware project yo build your own drone using a firmata-board compatible and johnny-five
> added node-open-pilot project

- lib/piezo.js
- test/piezo.js
Allow for custom piezo controller following [led controller](https://github.com/rwaldron/johnny-five/blob/master/lib/led/led.js#L142) property mix-in pattern. Mostly to support overriding of `setTone`/`noTone` per https://github.com/rwaldron/playground-io/pull/1, but may be of interest for #815.
@rwaldron let me know if you'd prefer I stub out more or use a different approach for mixing in, could do any of:
1. Stub out default controller behavior (add a `Controllers` map with an empty `DEFAULT`)
1. Move default piezo tone/no-tone behavior into the `DEFAULT` controller
1. Use some sort of different controller overriding pattern
TODO:
> Mix in controller properties for `Piezo`

- lib/gps.js
- test/gps.js
> Make baud property settable.

- lib/board.js
- test/sensor.js
Currently, adding custom properties like that is not supported:
```
mydevice.custom.foo = "bar";
```
and it fails with ```TypeError: Cannot set property 'foo' of null```
Changing default value from ```null``` to a real object would fix this.
> Default custom property to object literal instead of null

- lib/animation.js
- lib/servo.js
This works now
````
var five = require("johnny-five");
var Tessel = require("tessel-io");
var board = new five.Board({
io: new Tessel()
});
board.on("ready", function() {
var led = new five.Led("a5");
var fader = () => {
var easing = easingFns.shift();
led.off().fade({ easing }, 1000, fader);
};
fader();
});
var easingFns = [
"inQuad",
"outQuad",
"inOutQuad",
"inCube",
"outCube",
"inOutCube",
"inQuart",
"outQuart",
"inOutQuart",
"inQuint",
"outQuint",
"inOutQuint",
"inSine",
"outSine",
"inOutSine",
"inExpo",
"outExpo",
"inOutExpo",
"inCirc",
"outCirc",
"inOutCirc",
"inBack",
"outBack",
"inOutBack",
"inBounce",
"outBounce",
"inOutBounce",
];
````
We had two problems. 
First, temporal.stop was clearing out it's array of tasks on nextTick which meant that the next animation was already …
> animation-fixes

- lib/led/led.js
Was preparing for NBD and found that blink() did not work on Tessel 2 because pin mode was PWM and we weren't handling cases of ```state.value === 0``` for that.
This situation arises in experiment 1 of the guide for J5IK.
> Restore handling of 0 value

- lib/lcd.js
The LCD sleep function is currently implemented as follows:
```js
function sleep(ms) {
var start = Date.now();
while (Date.now() < start + ms) {}
}
```
As discussed [here](https://github.com/rwaldron/johnny-five/issues/326#issuecomment-230125813), the current implementation will often sleep for less than the requested number of milliseconds.
The modification to the sleep function introduced by this PR ensures that the sleep function sleeps for at least the requested number of milliseconds.
> Improve LCD millisecond delay handling

- lib/light.js
Should be scaled by 2^10, not by 2^16. See datasheet https://cdn-shop.adafruit.com/datasheets/TSL2561.pdf page 24
> Fixed scaling factors

- lib/light.js
This adds support for BH1750 light sensor, see datasheet info at http://rohmfs.rohm.com/en/products/databook/datasheet/ic/sensor/light/bh1750fvi-e.pdf
> Add support for BH1750 light sensor

- lib/imu.js
- test/hygrometer.js
- test/imu.js
- test/thermometer.js
This is a PR for fixing the timing issue and the int16/uint16 conversion issue discussed at #1253
> Multi: SHT31D wait 15ms for conversion and convert raw bytes to uint16

- test/animation.js
- test/repl.js
I believe I've identified and fixed the two top causes of flaky failures in the Travis CI builds. I've provided inline comments for each fix.
For a baseline, I looked at the last five builds on `master`: [2574](https://travis-ci.org/rwaldron/johnny-five/builds/222835946), [2573](https://travis-ci.org/rwaldron/johnny-five/builds/222109930), [2569](https://travis-ci.org/rwaldron/johnny-five/builds/221795739), [2568](https://travis-ci.org/rwaldron/johnny-five/builds/221793037), and [2567](https://travis-ci.org/rwaldron/johnny-five/builds/221778389).
- Total jobs: 50 (10 per build)
- Failures: 4 jobs / 8%
- `Animation -- Servo - keyframeEasing`
- [2574.6](https://travis-ci.org/rwaldron/johnny-five/jobs/222835952)
- `Cannot read property 'setUp' of undefined`
- …
> Make unit tests less flaky on Travis CI

- lib/piezo.js
- test/piezo.js
_Re-opening #1324, which automatically closed when I merged https://github.com/code-dot-org/johnny-five/pull/3; see that PR for discussion.  Sorry about that! FYI @rwaldron @lyzadanger_
The `note()` method was passing a frequency (Hz) to the `tone()` method, which is expecting to receive a duty cycle (μs), leading to the wrong note being played.  The solution is for `note()` to call `frequency()` instead, which will do the appropriate conversion.
Since it took me a while to understand the relationships between `tone`, `frequency` and `note` I've added some documentation to those methods to clear things up for the next person.  I've also made some unit tests more aggressive about checking that values are converted appropriately as they're passed around, and commented note-frequency-duty …
> Fix Piezo.prototype.note()

- test/collections.js
We [discussed here](https://github.com/rwaldron/johnny-five/commit/be3e8bd6211c6c1c1c25613d2bb7cc487466a581#commitcomment-21991716) a safe check for whether `Symbol` is available in the current node version (it's not, in node v0.10).  Three cases [were fixed here](https://github.com/rwaldron/johnny-five/commit/2884c2e5120b6eb1b8e91de806b238825ff68ba1) but a fourth was missed, causing tests to continue failing on node v0.10.x.  This fixes that fourth case.
> Fix tests on Node v0.10.x

- lib/thermometer.js
- test/board.js
- test/thermometer.js
Addresses https://github.com/rwaldron/johnny-five/issues/1297 by giving the `Thermometer` component `enable()` and `disable()` methods.
I've added tests but I'm a little confused by the structure of the Thermometer unit tests - this feature lives on the prototype and should be the same for all controllers, but it looks like it has to be tested per-controller?  But similar tests aren't applied to all controllers either.  Let me know if I should make sure these tests get added to every controller, or if we can run them just once on the default controller, etc.
Thanks!
> Give Thermometer enable/disable methods

- lib/animation.js
- test/extended/animation.js
> Fix support for synchronous animation queues

- lib/servo.js
- test/led.collection.js
- test/led.js
- test/servo.collection.js
- test/servo.js
When number is passed as the first keyframe of a servo animation it should be treated as a step from the most recent position.
Also adds tests for led to ensure that number values in first keyframe are still treated as explicit values.
Will close #1374 
Note that when this lands I need to update the animation wiki to better describe all devices that can be animated.
> Handle number as first value of servo keyframes

- lib/animation.js
- test/animation.js
- test/extended/animation.js
#1376 only fixed the problem when animation segments were enqueued in seperate passes through the event loop.  When two animation segments were enqueued on the same pass through the event loop we were starting both segments because the isRunning state was not being set until nextTick.
This should fix all that. I've updated some of the tests which I believe were written in a non-intuitive manner because of this bug. Instead of really understanding the problem I had just written the tests in a way that made them pass. There's probably a name for this sort of behavior. If not, we should invent a name.
> Fix sycnchronous animation queues

- lib/accelerometer.js
- test/accelerometer.js
The output of an ADXL345 accelerometer is scaled incorrectly when initialized with a `range` value other than 2g.  The output is scaled using the sensitivity value for 10-bit resolution, when it should be scaled using the sensitivity value for full-resolution.
This can be demonstrated with the following code:
```
const five = require('johnny-five')
const board = new five.Board()
board.on('ready', () => {
let accel = new five.Accelerometer({
controller: 'ADXL345',
range: 2
})
accel.on('change', () => {
console.log(accel.x, accel.y, accel.z)
})
})
```
Here is the (simplified) output using different values for `range` with the accelerometer lying flat on the table (Z-axis subject to a constant 1g):
* range=2: 0, 0, 1
* range=4: 0, 0, 2
* range=8: 0, 0, 4
* range=16: 0, 0, 8
Currently, the …
> ADXL345: Use full-resolution sensitivity for all ranges.

- lib/gyro.js
- test/gyro.js
Add test only for MPU6050 device.
Fix #1121 .
> Gyro: add MPU6050 and BNO055 devices resolution

- lib/board.js
- lib/repl.js
Reading issue #1406 I started playing with Board.detect and indeed in case
of no connection the function gets called with no throttling.
I found a couple of other things too:
* if a connected board(s) is(are) disconnected while running, when terminating the process the SIGINT event gets sometimes ignored (it has happened running a board with `repl: true` and `repl: false`)
* if multiple boards are connected with `repl: true`, when exiting the process an error is thrown because `state.board.io.pending` is not defined
In this PR a simple solution to the first problem follows what @dtex suggests in the issue discussion, while for the other two I add a fail safe timer of 1 second to force exit and fix the code in the `repl.js` module to handle the case of multiple boards.
This is not …
> Serial port list throttling and repl error with multiple boards

- README.md
- docs/servo-multi-turn.md
- eg/servo-multi-turn.js
- lib/esc.js
- lib/expander.js
- lib/servo.js
- test/animation.js
- test/board.js
- test/esc.js
- test/servo.collection.js
- test/servo.js
- tpl/programs.json
Previously #1387 
Servo values are now sent to io plug-ins in microseconds instead of degrees. This allows for better accuracy and different device ranges.
All servos now default to a PWM range of 600-2400 uS regardless of io-plugin being used (was a complete cluster before and couldn't be overridden on most platforms).
Adds new ```deviceRange``` property to servo opts that allows the user to specify the range of the servo. Defaults to 0-180°.
Changes the servo startAt value to be the center of the servo regardless of deviceRange unless otherwise specified by the user.
Adds servo multi-turn example
Updates PCA-9685 ```servoWrite()``` to allow values to be written in microseconds. This required updating esc as well.
Updates test.
Requires recent versions of most io-plugins (firmata.js was …
> Add support for multi-turn, winch, 90 and 360 degree servos

- lib/stepper.js
Added missing commas to some of the examples in the comments. For example, I changed this:
```js
five.Stepper({
type: five.Stepper.TYPE.FOUR_WIRE
stepsPerRev: number,
```
to this
```js
five.Stepper({
type: five.Stepper.TYPE.FOUR_WIRE,
stepsPerRev: number,
```
> Add missing commas in stepper comments

- lib/board.js
- lib/led/led.js
- lib/led/rgb.js
- lib/motor.js
- lib/pin.js
- test/board.js
- test/extended/servo.js
- test/led.js
- test/motor.js
- test/pin.js
- test/reflectancearray.js
- test/rgb.js
Required for ESP32. Addresses #1275, #1276, and #1280
> [WIP] Add support for PWM resolutions other than 8-bit

- lib/servo.js
- test/extended/servo.js
- test/servo.collection.js
- test/servo.js
If an array of keyFrames are passed to Servos, those keyFrames should be used as values for the whole collection and should not be normalized as a keyFrameSet.
> Fix for #1499

- docs/potentiometer.md
- eg/potentiometer.js
Currently, the schema uses A3 but the code uses A2.
I've updated the example to use A3.
> Use correct port for Potentiometer example

- lib/board.js
- lib/led/led.js
This variable is assigned twice in a row so I removed the first assignment.
I also decided to used the ternary operator to make the code more readable when returning the hardware.
> Remove useless var assignment

- docs/esc-PCA9685.md
- docs/esc-array.md
- docs/esc-bidirectional-forward-reverse.md
- docs/esc-bidirectional.md
- docs/esc-dualshock.md
- docs/esc-keypress.md
- eg/esc-PCA9685.js
- eg/esc-array.js
- eg/esc-bidirectional-forward-reverse.js
- eg/esc-bidirectional.js
- eg/esc-dualshock.js
- eg/esc-keypress.js
Updating the ESC examples that I've been looking at a bunch while preparing for Nodeboats at JSConf. Related to task discussed at recent collaborators mini-summit: https://github.com/rwaldron/johnny-five/issues/1588#issuecomment-521467213
The double-quote -> single-quote conversions were automated by my editor, so happy to change those back if needed.
> Docs: update ESC examples with newer javascript syntax

- docs/grove-light-sensor-edison.md
- docs/light-ambient-BH1750.md
- docs/light-ambient-EVS_EV3.md
- docs/light-ambient-EVS_NXT.md
- docs/light-ambient-TSL2561.md
- docs/light-reflected-EVS_EV3.md
- docs/light-reflected-EVS_NXT.md
- eg/arduino-starter-kit/light-theremin.js
- eg/grove-light-sensor-edison.js
- eg/light-ambient-BH1750.js
- eg/light-ambient-EVS_EV3.js
- eg/light-ambient-EVS_NXT.js
- eg/light-ambient-TSL2561.js
- eg/light-reflected-EVS_EV3.js
- eg/light-reflected-EVS_NXT.js
This updates the `light`  examples to es6. I used eslint to do most of the work and manually removed binds and a few other things.
Works #1596
> Examples: update light syntax

- package-lock.json
- package.json
This fix some vulnerabilities in dependencies, but still need to update (or maybe replace) [`grunt-jscs` ](https://www.npmjs.com/package/grunt-jscs) and [`copy-paste`](https://www.npmjs.com/package/copy-paste).
> chore(deps): update dependencies to fix vulnerabilities

- lib/motor.js
It is entirely reasonable to want to control a motor using a PCA9685 for speed and regular GPIO pins for direction. This PR allows for that.
Addresses #1624
> Add support for PCA9685_Hybrid motors

- lib/board.js
- package-lock.json
- package.json
- test/board-connection.js
- test/board.serial.js
- util/xbee.js
SerialPort v8 brings support for the latest versions of node and electron. The api has had two major breaking changes. `.list()` no longer takes a callback and only returns a promise. And the `PortInfo` object now has `path` instead of `comName`.
This PR probably requires a similar upgrade to firmata https://github.com/firmata/firmata.js/pull/201
I haven't tested this PR on hardware yet.
> chore: Upgrade SerialPort to v8

- lib/button.js
First, thanks a lot for this amazing library! 👏
In my project, I have buttons (with soft click) which trigger a lot of noise when pressing on it. I fixed the issue by increasing the debounce value of the button component. Would it be possible to expose an option to set this debounce value?
> feat(button): add a debounce time option

- lib/accelerometer.js
This PR fixes the bug described in #1709 by passing down the board reference given in the constructor.
Fixes https://github.com/rwaldron/johnny-five/issues/1709
> Accelerometer: Pass board reference through to Expander

- lib/led/rgb.js
- test/rgb.js
@code-dot-org/johnny-five was recently updated to the latest release of its upstream in [this PR](https://github.com/code-dot-org/johnny-five/pull/12). 
@islemaster - While implementing Code.org customizations, I noticed a small bug in `lib/led/rgb.js` - `RGB.prototype[Animation.keys]` is assigned to `RGB.colors` before `RGB.colors` is assigned to an array of strings. This PR changes the order of these lines.
[jira](https://codedotorg.atlassian.net/browse/SL-358)
> Assign colors, and then assign colors to keys

- lib/animation.js
- lib/led/led.js
- test/led.js
This PR changes `temporalTTL` in the `Animation` class to be configurable. @dtex @islemaster 
As stated in an [existing comment](https://github.com/rwaldron/johnny-five/blob/864f9b0e278397fc6c7f354da0de0ede2d4bc389/lib/animation.js#L271-L275),  a temporal animation segment can push CPU utilization to 100%. Currently, `temporalTTL` is set to 5000 ms so that if an animation runs for more than 5 seconds, the animation switches to using setInterval which is less accurate (by nanoseconds) but "perfectly serviceable". 
I removed the `temporalTTL` constant which was originally declared and assigned outside the `Rgb` class, and added it as an `Animation.Segment` option. Thus, if it is passed as a value through the segment, then the now local variable `temporalTTL` within the `Rgb` class will be …
> Modify Animation temporalTTL so that it is configurable

- docs/led-rgb-pulse.md
- lib/led/rgb.js
- test/rgb.collection.js
- test/rgb.js
Currently, the [Led class](https://github.com/rwaldron/johnny-five/blob/main/lib/led/led.js) contains both pulse and blink methods, but the [Rgb class](https://github.com/rwaldron/johnny-five/blob/main/lib/led/rgb.js) only contains the blink method. 
This PR adds a `pulse` method to the Rgb class. Note that the pulse method was recently [re-added](https://github.com/code-dot-org/johnny-five/pull/15) to the forked branch [`code-dot-org/johnny-five`](https://github.com/code-dot-org/johnny-five) after being updated to the latest release of upstream. The `pulse` method was first added to the Rgb class by @islemaster in [this PR](https://github.com/code-dot-org/johnny-five/pull/10).
I added the state value `isRunning` which was already a defined property in order to keep track of whether an …
> Add pulse method to RGB class

- docs/lcd-i2c-PCF8574.md
- eg/lcd-all.js
- eg/lcd-i2c-PCF8574.js
- lib/led/ledcontrol.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- eg/joystick-claw.js
- eg/joystick-motor-led.js
- eg/navigator-joystick.js
Fixes https://github.com/rwaldron/johnny-five/issues/1810
> Remove references to deprecated “axismove” event from Joystick examples
