- test/servo.js
Test for calling emit "move:complete" in the case where you call the same degree value twice.
Sorry the last PR got merged faster than I could add this. 
For testing this line:
https://github.com/rwaldron/johnny-five/blob/master/lib/servo.js#L286
> Test for "move:complete"

- CONTRIBUTING.md
Hey,
I noticed last week that there wasn't a contributing readme.  So I wrote one up that might help y'all when people are reporting issues, asking for new hardware support, writing docs, etc.
Could you read this and make suggestions on what else you think would be helpful to add. 
Also my spelling and grammar is sometimes bananas. :banana:
> contributing readme

- docs/piezo.md
- eg/piezo.js
- lib/piezo.js
- test/piezo.js
@rwaldron, @BrianGenisio
Following https://github.com/julianduque/j5-songs/pull/7
Please say if additional modifications are required.
> made piezo.play accept a string-encoded song

- .gitignore
we don't need these files to show up in git
> add npm-debug.log to .gitignore

- tpl/.readme.md
`Supported Hardware` section repeat twice with almost same content.
> remove `Supported Hardware` section  repeat

- tpl/titles.json
Need to regenerate readme following change
> shift register example typo

- docs/led-pulse.md
- eg/led-pulse.js
> Update LED Pulse example

- lib/board.js
- lib/motor.js
- lib/servo.js
Addresses #656
I do not recall why I commented this out in Servo & it never existed in Motor. It may have been a mistake, leftover from me trying to debug something.
Should we do this for other classes or it there a good reason it is not being done more?
> Wrap emitter.emit calls in process.nextTick

- docs/phoenix.md
- docs/servo-drive.md
- docs/servo.md
- eg/phoenix.js
- eg/servo-drive.js
- eg/servo.js
- lib/servo.js
- test/servo.js
Fixes #643. Updated all examples and docs as well. Still supports isInverted but console.warns.
> Change isInverted property to invert

- lib/led.js
- test/led.js
Fixes #681 
```js
color(Byte, Byte, Byte)
color([Byte, Byte, Byte])
color({
red: Byte,
green: Byte,
blue: Byte
});
color("#ffffff")
color("ffffff")
- color() => {r, g, b}
- color(...) => this
```
> Led.RGB.color signature additions

- Gruntfile.js
- docs/laser-trip-wire.md
- docs/lcd-i2c-PCF8574.md
- docs/magnetometer.md
- tpl/.breadboard.md
> ignore missing fzz in generated docs

- CONTRIBUTING.md
- README.md
- package.json
- tpl/.readme.md
this was distracting me too much, the last time was when browsing the [npm page](https://www.npmjs.com/package/johnny-five).
> rwldrn => rwaldron

- lib/led/rgb.js
- test/led.js
gets rid of RGB(Byte, Byte, Byte)
> drop back to one param for RGB constructor

- lib/servo.js
- test/servo.js
> support time/rate in min/max/center

- lib/led/led.js
Just some little stuff I noticed while reviewing `Led` to get an understanding of how the controller model works.
> Led: Cleanup

- lib/ir.js
- lib/led/ledcontrol.js
- lib/sonar.js
- lib/wii.js
- test/ledcontrol.js
- test/sonar.js
- test/wii.js
The only component I was able to test with a real device was `wii`, but the API change is very straight-forward.
> Update I2C API

- test/led.js
Here's the first phase of cleanup. Just the Led component so far. I'll get to the other components (Array, RGB, etc.) after.
> Led: Test cleanup

- lib/led/led.js
- test/led.js
> Led: Fix initialization of successive pins on PCA9685.

- lib/accelerometer.js
- test/accelerometer.js
Includes some other minor cleanup.
> Accelerometer: Add support for Esplora

- lib/led/led.js
- test/led.js
I asked @rwaldron about this the other day and he said there's no reason for this to stay around.
> Led: Remove type option

- lib/button.js
- test/button.js
> Button: refactor to controller design.

- docs/grove-lcd-rgb-temperature-display.md
- docs/grove-lcd-rgb.md
- docs/grove-sensor.md
- docs/temperature-mpu6050.md
- eg/grove-lcd-rgb-temperature-display.js
- eg/grove-lcd-rgb.js
- eg/grove-sensor.js
- eg/temperature-mpu6050.js
I ran a site crawl on http://johnny-five.io and there were several broken links in the example files.  I've updated them as best I know.  They probably need verified that I picked the right images.
* Fixing broken link to the MPU-6050
* fixed broken images for grove temperature and rotary
* updated examples
> Fixing broken links and images

- test/board.js
- test/pin.js
> Cleanup tests, purge boards. Fixes gh-827

- lib/sensor.js
- test/sensor.js
Restructure analog sensor shape test to check that all and only expected properties and methods exist
Verify that expected default property values are set
Check that data events are emitted at the expected time tick
Check that median processing give the expected results and emitted events
> Expand test cases for the sensor class, and fix median value handling

- lib/led/rgb.js
- test/led.js
Fixes #737 
Alternative to #818, storing the intensity as separate state from color.
> Led.RGB: Add intensity method

- docs/led-rainbow.md
- docs/led-rgb.md
- tpl/programs.json
Also made description in led-rgb consistent with other examples
> wrong diagram/desc for RGB rainbow example

- lib/board.js
So this setTimeout was being kicked off even though we're using mock-serial and that's what was eventually causing our unspecified error.
> When using mock-serial we should always assume success

- .travis.yml
Seems to work fine. Also noticed it kicked off much more quickly than usual. Addresses #863
> Upgrade to Travis container based infrastructure

- README.md
- docs/micromagician-accelerometer.md
- docs/micromagician-motor.md
- docs/micromagician-servo.md
- eg/micromagician-accelerometer.js
- eg/micromagician-motor.js
- eg/micromagician-servo.js
- lib/motor.js
- tpl/programs.json
Title says it all. Realized this probably doesn't count as a new board since it's Arduino Pro compatible. Just added examples in case someone comes here looking for J5 support on the device.
> Add Micro Magician examples and Shield Config

- lib/temperature.js
- test/temperature.js
I moved some stuff around in the test suite too.
Are there newer patterns for modules that this section should be brought up to date with?  It was actually a little difficult for me to work in this test suite, happy to do some cleanup here if there is work to do.
> Temperature: Add C, K, F values to the data event and temperature objects

- lib/temperature.js
- test/temperature.js
I'm not sure - but it seems that the math involved for these two controllers doesn't take aref into account at all.
> Complete test conversion for analog controllers and aref

- docs/temperature-tmp36.md
- eg/temperature-tmp36.js
Removed unused variable sensor
> Removed unused variable from the example for Temperature sensor TMP36

- tpl/programs.json
Removed extra ) in "Infrared Reflectance)", in tpl/programs.json
:)
> Infrared Reflectance)

- lib/sensor.js
- test/sensor.js
> Sensor: Default to 50% of scaled values for boolean barrier

- lib/piezo.js
> Piezo: Make `isPlaying` readonly

- lib/thermometer.js
SI7020 Thermometer: Wrong Temperature Calculation
> Suggested bug fix for issue #972

- tpl/.readme.md
Hope this works! I saw that the "Prerequisites" link doesn't work.
> Updated link to Prerequisites

- lib/servo.js
- test/servo.js
Returns the servo to its startAt position. 
For a single servo it's just sugar for ```servo.to(servo.startAt)```
For a servo array it will return each servo to its own startAt value (handy for setting chains to their home positions).
> Add Servo.home()

- lib/led/ledcontrol.js
I learned about how the LED controller works today and added docs. Feedback welcome, generally adhered to JSDoc standard.
> LED controller documentation

- lib/wii.js
Very late follow up to #726.
Unfortunately, I don't have a classic controller and I broke a pin on my nunchuk, so I couldn't test this with real hardware. I just ordered both on eBay, so if you want this verified with real hardware and nobody else can test in the next few weeks, I'll eventually be able to test this.
> Wii: Cleanup

- lib/board.js
Suggested fix for issue #1053. 
I am also happy to edit the board Wiki page accordingly. Please advise.
> Made board ready timeout configurable. 

- eg/sensor.js
> Use value read instead of a new one

- lib/lcd.js
- lib/led/rgb.js
- package.json
Updated color-convert to the latest version.
Tests were already failing so not sure what was up there.
> Update color-convert to 1.2.2

- eg/gps.js
I add more event to example and more value to show in change event.
And correct wrong comment above change event which is not involve to speed and course.
> Add more event example and correct the commend

- lib/array-includes-shim.js
Add "includes" Array.prototype function as a non-enumerable member, https://github.com/rwaldron/johnny-five/issues/1113
> Suggested fix for #1113

- eg/brat.js
Looks like this should be `left.hip === 90`
> Repeated subexpression in brat.js

- lib/piezo.js
- test/piezo.js
> Prevent `Piezo#play` from mutating `song` array

- .gitignore
- package.json
Give the grunt cli js path for istanbul on windows
> npm binaries are in the path for npm scripts

- docs/button-options.md
- eg/button-options.js
button-options.fzz and button-options.png:   pin '8'
but source code and doc:  pin '7'
* docs/breadboard/button-options.png
* docs/breadboard/button-options.fzz
> fix pin 7->8 in button-options.

- lib/fn.js
- test/fn.js
As the first part of creating some docs for `lib/Fn.js` #1214 , I've added and updated commenting in source. I've also shored up tests, though it was in a pretty good place to start with. At this point, we've got fully 100% coverage.
A few notes:
* I didn't try to meaningfully comment the `fma` function because it's, ah, a bit beyond my grade level.
* I was a tad confused by the behavior of the auto-generated `Fn.u*` functions, which I believe are meant to constrain the passed value to a certain bit size. `Fn.u8(256)` returns `256`. Isn't that a 9-bit number? I may completely not understand what those functions are for, though :).
> `lib/Fn.js` Clean up and Commenting

- lib/lcd.js
HD44780 is not actually a controller but a type of screen
> remove controller alias for HD44780

- docs/led-rainbow.md
- eg/led-rainbow.js
Loop didn't go through entire rainbow array. The last element was
omitted.
> Led.RGB: Fix example "LED - Rainbow"

- lib/lcd.js
Actually, only the first 8 predefined characters will be load. After 8 "useChar", it is not possible to change/replace character in LCD memory.
This fix allow to use the 8 LAST predefined characters defined with "useChar".
> Use more then 8 predefined characters

- lib/imu.js
- test/hygrometer.js
- test/thermometer.js
Fixes https://github.com/rwaldron/johnny-five/issues/1278
> Multi: HTU21D convert raw bytes to uint16

- lib/accelerometer.js
- test/accelerometer.js
Fixes https://github.com/rwaldron/johnny-five/issues/1152
> Accelerometer: ADXL345 use typical sensitivity

- lib/thermometer.js
- test/thermometer.js
Fixes https://github.com/rwaldron/johnny-five/issues/1298
> Thermometer: LM35/LM335/TMP36 max raw value 1023

- lib/expander.js
- test/expander.js
@fivdi can you try your code with this branch and without your explicit addresses? Thanks!
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
> Expander: don't require an address when unnecessary. Fixes gh-1291

- lib/lcd.js
> LCD: Wait for fast instructions to complete

- .travis.yml
- appveyor.yml
- tpl/.readme.md
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
> ci: remove node 5, add node 8

- lib/thermometer.js
- package.json
- test/thermometer.js
This adds support for having multiple driver instances for the DS18B20 on different pins (1wire bus) concurrently. This has been tested in real-life using 6 thermos, 3 on each of 2 different pins. Works great!
> Multi-pin DS18B20

- lib/servo.js
- test/servo.js
> Servo values were being inverted twice when Servo.to() was called with a time

- lib/motor.js
- test/motor.js
> Require motor pins

- lib/altimeter.js
- test/altimeter.js
> Altimeter fixed point values

- lib/accelerometer.js
- test/accelerometer.js
Add device sensitivity to `toGravity.value` and test
case.
> Accelerometer: add LIS3DH fractional digits

- lib/servo.js
- test/extended/servo.js
- test/servo.js
> Servo bug fixes

- lib/hygrometer.js
- test/hygrometer.js
Add resolutions and tests (where implemented) of hygrometer class devices.
Fix #1122
> Hygrometer fixed point values

- README.md
- docs/motor-drv8871.md
- eg/motor-drv8871.js
- tpl/programs.json
Adds example for [Adafruit DRV8871](https://www.adafruit.com/product/3190)
Closes #1459
> DRV8871 Example

- README.md
- tpl/.readme.md
This adds a badge to display the npm install size.
> Add badge to display install size

- lib/gps.js
Addresses rwaldron/tessel-io#23
> Do not require SERIAL_PORT_IDs

- docs/raspi-io.md
- eg/raspi-io.js
- package-lock.json
Addresses https://github.com/nebrius/raspi-io/issues/118
> Update RaspberryPi example

- README.md
- docs/esc-PCA9685.md
- docs/esc-bidirectional.md
- eg/esc-PCA9685.js
- eg/esc-array.js
- eg/esc-bidirectional.js
- eg/esc-blobfish.js
- eg/esc-keypress.js
- lib/esc.js
- lib/expander.js
- lib/sleep.js
- test/esc.js
- tpl/programs.json
- Eliminates "history" memory leak
- Deprecates speed()
- Introduces throttle(us)
> ESC: deprecate speed(percent), introduce throttle(us).

- docs/esc-array.md
- docs/esc-bidirectional-forward-reverse.md
- docs/esc-dualshock.md
- eg/esc-bidirectional-forward-reverse.js
- eg/esc-dualshock.js
Found some example programs that I missed when reviewing #1484.
> Update ESC examples to new API methods

- docs/raspi-io.md
- eg/raspi-io.js
https://github.com/nebrius/raspi-io/blob/master/CHANGELOG.md#1000-2019-2-21
> Update example after raspi-io v10.0.0

- README.md
- docs/motor-vnh5019.md
- tpl/programs.json
I also noticed that this doc file was not being generated, so I added it.
> Fix error in VNH5019 example

- eg/sonar-scan.js
- eg/sonar-srf10.js
- eg/sonar.js
I'm assuming these are removed from programs.json because Sonar has been dropped in favor of proximity.
> Sonar examples

- lib/expander.js
> Disable all call

- docs/altimeter-mpl3115a2.md
- eg/altimeter-mpl3115a2.js
> fix: variable name

- docs/shift-register-daisy-chain-anode.md
- docs/shift-register-daisy-chain.md
- docs/shift-register-seven-segment-anode.md
- docs/shift-register-seven-segment.md
- docs/shift-register.md
- eg/.jshintrc
- eg/shift-register-daisy-chain-anode.js
- eg/shift-register-daisy-chain.js
- eg/shift-register-seven-segment-anode.js
- eg/shift-register-seven-segment.js
- eg/shift-register.js
- eg/shiftregister.js
I tried to remove the async dependency and add a couple of functions to replace it, but I had JSHint issues and let it go for now.
> Update shift register examples

- docs/imu-bno055-orientation.md
- docs/imu-bno055.md
- docs/imu-lsm303c.md
- docs/imu-mpu6050.md
- eg/imu-bno055-orientation.js
- eg/imu-bno055.js
- eg/imu-lsm303c.js
- eg/imu-mpu6050.js
> docs: update IMU examples

- awesome.md
Add my drawing robot to the awesome list.
> update awesome.md adding new robot to put as sample
